orbs:
  architect: giantswarm/architect@2.1.0

version: 2.1
workflows:
  build:
    jobs:
      # build operator
      - architect/go-build:
          name: go-build
          binary: upgrade-operator
          resource_class: xlarge
          filters:
            tags:
              only: /^v.*/

      # build and push docker image to quay.
      - architect/push-to-docker:
          name: push-upgrade-operator-to-quay
          image: "quay.io/giantswarm/upgrade-operator"
          username_envar: "QUAY_USERNAME"
          password_envar: "QUAY_PASSWORD"
          requires:
            - go-build
          filters:
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/

      # build and push helm chart to app catalog.
      - architect/push-to-app-catalog:
          name: push-upgrade-operator-to-control-plane-app-catalog
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "upgrade-operator"
          # Make sure docker image is successfully built.
          requires:
            - push-upgrade-operator-to-quay
          filters:
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/
