
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - bootstrap.cluster.x-k8s.io
  - cluster.x-k8s.io
  - controlplane.cluster.x-k8s.io
  - exp.cluster.x-k8s.io
  - exp.infrastructure.cluster.x-k8s.io
  - infrastructure.cluster.x-k8s.io
  resources:
  - awsclusters
  - awsclusters/status
  - awsmachinepools
  - awsmachinepools/status
  - awsmachinetemplates
  - azureclusters
  - azureclusters/status
  - azuremachinepools
  - azuremachinepools/status
  - azuremachinetemplates
  - clusters
  - clusters/status
  - kubeadmconfigtemplates
  - kubeadmcontrolplanes
  - machinedeployments
  - machinedeployments/status
  - machinepools
  - machinepools/status
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - awsmachinetemplates
  - azuremachinetemplates
  verbs:
  - create
- apiGroups:
  - release.giantswarm.io
  resources:
  - releases
  verbs:
  - get
  - list
  - watch
